### ISSUE TITLE
Incompatible with Yarn PnP

### ISSUE THREAD

**Issue by retrixe** [mightyiam/eslint-config-love#1801]
Using this configuration with the Yarn package manager (in its default PnP mode) results in the following error:
```
❯ yarn lint

Oops! Something went wrong! :(

ESLint: 8.57.1

Error: eslint-config-love tried to access @typescript-eslint/utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @typescript-eslint/utils
Required by: eslint-config-love@virtual:8e8c832788447b1439f7347fe921d2f30424373bd77c2e629f25eb152bdbf15de051a1b34b6954ff3b5a022ec23312682697f398ce2bd317fa88e10f08f71ee1#npm:84.1.0 (via /home/ideapad/Documents/salezy/server/.yarn/__virtual__/eslint-config-love-virtual-1c3c95474c/4/.yarn/berry/cache/eslint-config-love-npm-84.1.0-7f31c71c7c-10c0.zip/node_modules/eslint-config-love/lib/)

Require stack:
- /home/ideapad/Documents/salezy/server/.yarn/__virtual__/eslint-config-love-virtual-1c3c95474c/4/.yarn/berry/cache/eslint-config-love-npm-84.1.0-7f31c71c7c-10c0.zip/node_modules/eslint-config-love/lib/index.js
    at require$$0.Module._resolveFilename (/home/ideapad/Documents/salezy/server/.pnp.cjs:10863:13)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at require$$0.Module._load (/home/ideapad/Documents/salezy/server/.pnp.cjs:10754:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/home/ideapad/Documents/salezy/server/.yarn/__virtual__/eslint-config-love-virtual-1c3c95474c/4/.yarn/berry/cache/eslint-config-love-npm-84.1.0-7f31c71c7c-10c0.zip/node_modules/eslint-config-love/lib/index.js:25:17)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
```

**Comment by mightyiam** [comment]
Thank you, @retrixe
